trigger:
  branches:
    include:
      - main
  paths:
    exclude:
     - azure-pipelines.yml
     - azure-pipelines-cd.yml

pool:
  vmImage: ubuntu-latest


steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '24.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npm test
    displayName: 'Run tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        public/**
        src/**
        package.json
        package-lock.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Prepare application artifact'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'webapp'
      publishLocation: 'Container'
    displayName: 'Publish artifact'
 
